### PR TITLE
Multi calendar

### PR DESCRIPTION
**Pull request by agroszer**
comments addressed

### CODE REVIEW

**Comment by agroszer** [comment]
sigh... I might need to start over?

**Comment by derekantrican** [comment]
I can take a look at it later today

**Comment by agroszer** [comment]
Basically just wanted to amend e72b7436f582b807eb5b00d78a08697e9cdda797, but apparently github+git+fork does not make that easy

**Comment by derekantrican** [comment]
@agroszer I am going to wait on these changes until https://github.com/derekantrican/GAS-ICS-Sync/pull/31 is approved and completed because it has some structural changes in it

Feel free to take a look at it and approve or add comments

**Comment by agroszer** [comment]
yeah no worries, meanwhile I'm having the patched code running for me

**Comment by derekantrican** [comment]
Closing this PR as we have multi calendar support in the next version

**Pull request closed without merging**
