### PR TITLE
no add alert reverts to calendar's default alert

### PR DESCRIPTION
**Pull request by rufuswilson**
When addAlert is set to false, the event will have the default alerts of the calendar.
I would have expected that it would not have any alerts at all.

### CODE REVIEW

**Comment by derekantrican** [comment]
I understand the confusion, though I feel like this could still be a desired behavior. Maybe we should treat it more as an enum (addAlerts: yes/no/default)? @jonas0b1011001 thoughts?

**Comment by rufuswilson** [comment]
I actually very much like the idea

**Comment by derekantrican** [comment]
Seems fine to me. If Jonas doesn't have any thoughts I'll merge it in

**Comment by jonas0b1011001** [comment]
I'm happy with the changes

**Comment by rufuswilson** [comment]
Just before you merge them, I would like to test the default option. Just
realized I didn't test it yet





---------------------------------------------------
Tchô

**Comment by jonas0b1011001** [comment]
> When addAlert is set to false, the event will have the default alerts of the calendar.

So seems like we could go with _doing nothing_ as the default option

**Comment by rufuswilson** [comment]
By “doing nothing” you mean using the calendar’s default notifications or not having any notifications at all?



---------------------------------------------------
Tchô

**Comment by rufuswilson** [comment]
Finished the testing and all options behave as they should.

**Comment by derekantrican** [comment]
I think the changes seem fine to me. Glad you've also got the `default: ` in your switch-case (and I think "target calendar default" is a fine default)

**Pull request merged**
